### ISSUE TITLE
Backend subprocess exited when trying to invoke get_requires_for_build_sdist

### ISSUE THREAD

**Issue by AlaiY95** [lindosystems/lindoapi-python#1]
I'm installing lindoapi-python using the readme but i'm running into the following issue:

```
C:\Users\alaiy>cd c:\Lindoapi

c:\Lindoapi>set LINDOAPI_HOME="c:/lindoapi"

c:\Lindoapi>pip install lindo
Requirement already satisfied: lindo in c:\users\alaiy\appdata\local\programs\python\python38\lib\site-packages (13.0.0)
Requirement already satisfied: numpy>=1.19 in c:\users\alaiy\appdata\local\programs\python\python38\lib\site-packages (from lindo) (1.22.3)
WARNING: You are using pip version 20.2.3; however, version 22.0.4 is available.
You should consider upgrading via the 'c:\users\alaiy\appdata\local\programs\python\python38\python.exe -m pip install --upgrade pip' command.

c:\Lindoapi>pip install numpy
Requirement already satisfied: numpy in c:\users\alaiy\appdata\local\programs\python\python38\lib\site-packages (1.22.3)
WARNING: You are using pip version 20.2.3; however, version 22.0.4 is available.
You should consider upgrading via the 'c:\users\alaiy\appdata\local\programs\python\python38\python.exe -m pip install --upgrade pip' command.

c:\Lindoapi>python -m build
ERROR Source c:\Lindoapi does not appear to be a Python project: no pyproject.toml or setup.py

c:\Lindoapi>cd python

c:\Lindoapi\python>python -m build
* Creating venv isolated environment...
* Installing packages in isolated environment... (setuptools >= 40.8.0, wheel)
* Getting dependencies for sdist...

Warning: numpy was not found, installing...

Collecting numpy
  Using cached numpy-1.22.3-cp38-cp38-win_amd64.whl (14.7 MB)
Installing collected packages: numpy
Successfully installed numpy-1.22.3
WARNING: You are using pip version 20.2.3; however, version 22.0.4 is available.
You should consider upgrading via the 'C:\Users\alaiy\AppData\Local\Temp\build-env-42ysu686\Scripts\python.exe -m pip install --upgrade pip' command.
Traceback (most recent call last):
  File "C:\Users\alaiy\AppData\Local\Programs\Python\Python38\lib\site-packages\pep517\in_process\_in_process.py", line 363, in <module>
    main()
  File "C:\Users\alaiy\AppData\Local\Programs\Python\Python38\lib\site-packages\pep517\in_process\_in_process.py", line 345, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "C:\Users\alaiy\AppData\Local\Programs\Python\Python38\lib\site-packages\pep517\in_process\_in_process.py", line 297, in get_requires_for_build_sdist
    return hook(config_settings)
  File "C:\Users\alaiy\AppData\Local\Temp\build-env-42ysu686\lib\site-packages\setuptools\build_meta.py", line 181, in get_requires_for_build_sdist
    return self._get_build_requires(config_settings, requirements=[])
  File "C:\Users\alaiy\AppData\Local\Temp\build-env-42ysu686\lib\site-packages\setuptools\build_meta.py", line 159, in _get_build_requires
    self.run_setup()
  File "C:\Users\alaiy\AppData\Local\Temp\build-env-42ysu686\lib\site-packages\setuptools\build_meta.py", line 281, in run_setup
    super(_BuildMetaLegacyBackend,
  File "C:\Users\alaiy\AppData\Local\Temp\build-env-42ysu686\lib\site-packages\setuptools\build_meta.py", line 174, in run_setup
    exec(compile(code, __file__, 'exec'), locals())
  File "setup.py", line 45, in <module>
    LSVERSION,szMajorVer,szMinorVer = ls_get_version(API_HOME + "/include/lsversion.sh")
  File "setup.py", line 20, in ls_get_version
    for line in fileinput.input(filename):
  File "C:\Users\alaiy\AppData\Local\Programs\Python\Python38\lib\fileinput.py", line 248, in __next__
    line = self._readline()
  File "C:\Users\alaiy\AppData\Local\Programs\Python\Python38\lib\fileinput.py", line 366, in _readline
    self._file = open(self._filename, self._mode)
OSError: [Errno 22] Invalid argument: '"c:/lindoapi"/include/lsversion.sh'

ERROR Backend subproccess exited when trying to invoke get_requires_for_build_sdist
```

Any ideas?

**Comment by AlaiY95** [comment]
Found a fix.. In the environment variables setting window I changed the value to 'LINDOAPI_HOME'  as line 45 ''' LSVERSION,szMajorVer,szMinorVer = ls_get_version(API_HOME + "/include/lsversion.sh") ''' was the error which uses API_HOME = os.environ.get('LINDOAPI_HOME') :)

**Comment by mkatlihan** [comment]
LINDOAPI_HOME variable should have been set correctly (and it has to be a valid folder name).

**Comment by AlaiY95** [comment]
Thanks I did everything except for update the directory for the path thanks!
